[package]
name = "lifecycle"
version = "0.1.0"
edition = "2024"

[lib]
name = "lifecycle"
path = "src/lib.rs"

[[bin]]
name = "lifecycle"
path = "src/main.rs"

[dependencies]
bevy = "0.16.1"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
